[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; USB CDC on boot (Serial over native USB)
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

; OPTIONAL but strongly recommended: decode the backtrace
monitor_filters = esp32_exception_decoder

lib_deps =
    https://github.com/sparkfun/SparkFun_BMV080_Arduino_Library
    GXEPD2
    7Semi BME690
    Sensirion I2C STCC4
    constiko/RTC RV-3028-C7 Arduino Library@^2.1.0
    adafruit/Adafruit MAX1704X@^1.0.3
